<?php
$page_title="Engineering";
 $program_title="Engineering";
 $videoId="";
 $replacementImg="../assets/engineering/topImage.jpg";
 $programOverview=""; 
 $classOneTitle="Introduction to Engineering Design (IED)";
 $classOneInfo="Ever wondered how to design something new or draw out an idea to show your friends? Stop wondering and do it, using Autodesk Inventor, the industry-leading 3D design software! Discover the role of an engineer in taking an idea from the design process to manufacturing or production. Produce an incredible, working prototype of your project with a 3D printer. You will work on projects, activities, and problems not only of interest to you, but that have global and human impacts. Work in teams to design and improve products, document your solutions, and communicate them to others.";
 $classTwoTitle="Principles of Engineering (POE)";
 $classTwoInfo="Go beyond “myth buster” to solution builder! As you master the basic concepts needed to continue your education in engineering, you’ll apply them — tackling real world challenges in the areas of energy sources, electronics, and applications, machine systems, mechanisms, robotic programming, fluid power, testing the strength and durability of materials, kinematics and projectile motion, and understanding how things move and applying that knowledge to projects. You are not in this alone: team up with other students to test and share your developing skills and problem-solving ability through hands-on projects and presentations."; 
 $classThreeTitle="Computer Integrated Manufacturing (CIM)";
 $classThreeInfo="Learn up close how things are made. Is the process for making a water bottle the same as a musical instrument? How are assembly lines designed and automated? Through your growing knowledge of the history, principles, and processes of manufacturing, you will design and build your own automated manufacturing system, factoring in safety, quality, cost, and efficiency. Use technologies in your projects that have revolutionized manufacturing: computer modeling, Computer Numeric Control (CNC) technology, Computer Aided Manufacturing (CAM) software, robotics, and flexible manufacturing systems.";
 $classFourTitle="Civil Engineering and Architecture (CEA)";
 $classFourInfo="Use 3D modeling software AutoDesk Revit Architecture to create and test your own residential and commercial designs, factoring in things like materials and systems, structural design, cost / efficiency analysis, stormwater management, site design and considerations, utilities and services, building codes, and architectural style and guidelines. Research the careers and trends in the design and construction industry, including new developments in energy efficiency, green technologies, and changing populations. Be inspired to shape the spaces of the 21st Century!"; 
 $classFiveTitle="Digital Electronics (DE)";
 $classFiveInfo="Analyze, design, and build your own digital electronic circuits, the technology that powers your cell phone, MP3 player, tablet, camera, and HD television. The demand for greater signal speed, storage capacity, and applications drives industry’s need for creative problem solvers and innovators like you! Start with the basics: theory, terminology, communication methods, engineering standards, and troubleshooting techniques. Before you know it, you will be programming microchips and a basic stamp microcontroller. DE is one of the specialized courses in the Project Lead The Way (PLTW) “Pathway to Engineering” course sequence. Prior completion of the IED and POE foundation courses (through TCD or your high school) is suggested, though not required."; 
 $classSixTitle="";
 $classSixInfo="";
 $galleryImgs=["../assets/engineering/gallery1.jpg","../assets/engineering/gallery2.jpg","../assets/engineering/gallery3.jpg","../assets/engineering/gallery4.jpg","../assets/engineering/gallery5.jpg","../assets/engineering/gallery6.jpg"];
 $certifications="";
 $certificationsImg="";
 $certificationsName="";
 $partners="";
 $partnersImg="";
 $partnersName="";
 $dualCredit="Students can earn up to 12 free dual credits: </p><p>6 in PLTW Introduction to Engineering and Production</p><p>3 in PLTW Principles of Engineering</p><p>3 in Civil Engineering and Architecture</p><p>3 in Computer Integrated Manufacturing</p><p>Students can also earn 3 in Digital Electronics through Vincennes University.</p>";
 $dualCreditImg="https://www.ivytech.edu/images/ivy-tech-2015-logo_header.png";
 $dualCreditImg2="../assets/cosmetology/vu_logo.png";
 $dualCreditName="Ivy Tech";
 $dualCreditName2="Vincennes University";
 $internships="";
 $internshipsImg="";
 $internshipsName="";
 $testimonies=["The best impact of the Walker Career Center’s pre-engineering program is that it provides high school students with hands-on experiences of real engineering processes at a very early stage in their careers.  The experience I gained has led me to pursue engineering as a lifelong passion.","The engineering program is hands down the most influential experience you can go through, not only for people interested in engineering but those who just want to experience the world on a whole new level. It was genuinely so captivating and educating, that I would have been willing to go through it a hundred more times."," The pre engineering program is the perfect way to jumpstart your career. Not only that, but if you really take advantage of it and the knowledge offered by it, you can have some of the best times of your life.","The engineering program at the Walker Career Center is top tier.  Not only did the technical skills I developed during my time there help me tremendously at Purdue, they also gave me a leg up on all of my peers coming in as a freshman."," I love that it shows different areas of engineering and it offered many opportunities both inside and outside of the classroom.  I also really enjoyed how engaging the projects were.","Personally, it was engaging and showed a variety of opportunities, which allowed me to hone in on the major that worked best for me.","The engineering program at the Walker Career Center was an opportunity that has inspired me for life.","Through the years of being in Engineering, I have always enjoyed the freedom we are given when it comes to creativity. This freedom has allowed me to really discover my interests in programming and working with robots or even running CNC mills. I most definitely recommend this program to anyone with some interests in robots or the understanding of engineering as these classes have given me a wide range of skills and information."];
 $testimoniesName=["Brian Wyatt (Class of 2015)"," Rebecca Clark (Class of 2020)","Knight Wolff (Class of 2020)","Johnny Walker (Class of 2017)","Jaidy Hernandez (Class of 2015)","Gabby Bettegnies (Class of 2015)"," Dawson Willis (Class of 2016)","Hayden Schell (Class of 2021)"];
 $extraImgs=["../assets/engineering/extra1.jpg","../assets/engineering/extra2.jpg","../assets/engineering/extra3.jpg","../assets/engineering/extra4.jpg","../assets/engineering/extra5.jpg","../assets/engineering/extra6.jpg"];
 $grade1="Freshman";
 $grade2="Sophomore";
 $grade3="Junior";
 $grade4="Junior";
 $grade5="Senior";
 $teacher1="Mr. Hanson";
 $teacher2="Mr. Hanson";
 $teacher3="Mr. Hanson";
 $teacher4="Mr. Hanson";
 $teacher5="Mr. Hanson";
 $prerequisites1="Students entering as Freshmen need to be enrolled in Geometry";
 $prerequisites2="";
 $prerequisites3="Introduction to Engineering OR Principles of Engineering";
 $prerequisites4="Introduction to Engineering OR Principles of Engineering";
 $prerequisites5="Introduction to Engineering OR Principles of Engineering";
 
 
 include($_SERVER["DOCUMENT_ROOT"] . '/program.php');
?>