<?php
$page_title="Marketing";
 $program_title="Marketing";
 $videoId="";
 $replacementImg="";
 $programOverview=""; 
 $classOneTitle="Introduction to Business";
 $classOneInfo="Introduction to Business introduces students to the world of business, including the concepts, functions, and skills required for meeting the challenges of operating a business.  The course covers business management, entrepreneurship,marketing fundamentals, and business ethics and law.";
 $classTwoTitle="Principles of Marketing";
 $classTwoInfo="Principles of Marketing provides a basic introduction to the scope and importance of marketing in the global economy. The course covers the primary marketing functions: of advertising/promotion/selling, distribution, financing, marketing-information management, pricing, and product/service management."; 
 $classThreeTitle="Strategic Marketing";
 $classThreeInfo="Strategic Marketing builds upon the foundations of marketing and applies the functions of marketing at an advanced level. Students will study the basic principles of consumer behavior and examine the application of theories from psychology, social psychology, and economics and the relationship between consumer behavior and marketing activities.";
 $classFourTitle="";
 $classFourInfo="";
 $galleryImgs="";
 $certifications="";
 $certificationsImg="";
 $certificationsName="";
 $partners="";
 $partnersImg="";
 $partnersName="";
 $dualCredit="Student can earn up to 9 free daul credits: 6 in Principles of Marketing and 3 in Strategic Marketing";
 $dualCreditImg="https://www.ivytech.edu/images/ivy-tech-2015-logo_header.png";
 $dualCreditImg2="../assets/cosmetology/vu_logo.png";
 $dualCreditName="Ivy Tech";
 $dualCreditName2="Vincennes University";
 $internships="";
 $internshipsImg="";
 $internshipsName="";
 $testimonies=[""];
 $testimoniesName=[""];
 $extraImgs="";
 $grade1="Sophomore";
 $grade2="Junior";
 $grade3="Senior";
 $grade4="";
 $teacher1="Mr. Huggins, Mrs. Williams";
 $teacher2="Ms. Colville";
 $teacher3="Ms. Colville";
 $teacher4="";
 $prerequisites1="";
 $prerequisites2="Intro to Business";
 $prerequisites3="Principles of Marketing";
 $prerequisites4=""; 
 
 include($_SERVER["DOCUMENT_ROOT"] . '/program.php');
?>